version: '3.4'

services:
  book:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  member:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  order:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  review:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

