version: '3.4'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    
  adminer:
    image: adminer
    depends_on: 
      - db
      
  coreapigateway:
    image: ${DOCKER_REGISTRY-}coreapigateway
    build:
      context: .
      dockerfile: ApiGateways/CoreApiGateway/Dockerfile
    depends_on: 
      - review
      - order
      - member
      - book


  review:
    image: ${DOCKER_REGISTRY-}review
    build:
      context: .
      dockerfile: Services/Review/Dockerfile
    depends_on: 
      - db


  order:
    image: ${DOCKER_REGISTRY-}order
    build:
      context: .
      dockerfile: Services/Order/Dockerfile
    depends_on: 
      - db


  member:
    image: ${DOCKER_REGISTRY-}member
    build:
      context: .
      dockerfile: Services/Member/Dockerfile
    depends_on: 
      - db


  book:
    image: ${DOCKER_REGISTRY-}book
    build:
      context: .
      dockerfile: Services/Book/Dockerfile
    depends_on: 
      - db

