version: "3.4"

services:
  db:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      #- db-data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
      #- ./db-data/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - app-network

  seq:
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
    #volumes:
    #  - ./seq-data:/data
    networks:
      - app-network

  adminer:
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-network

  coreapigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "5100:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - app-network

  review:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=services_computing_review;Username=postgres;Password=postgres;
    ports:
      - "80"
      - "5200:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - app-network

  order:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=services_computing_order;Username=postgres;Password=postgres;
    ports:
      - "80"
      - "5201:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - app-network

  member:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=services_computing_member;Username=postgres;Password=postgres;
      - Serilog__WriteTo__0__Args__serverUrl=http://seq
    ports:
      - "80"
      - "5202:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - app-network

  book:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=services_computing_book;Username=postgres;Password=postgres;
    ports:
      - "80"
      - "5203:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - app-network

volumes:
  db-data:
    driver: local

networks:
  app-network:
    name: "honours_project_network"
