version: '3.4'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    
  adminer:
    image: adminer
    depends_on: 
      - db
      
  coreapigateway:
    image: ${DOCKER_REGISTRY-}coreapigateway
    build:
      context: .
      dockerfile: ApiGateways/CoreApiGateway/Dockerfile


  review:
    image: ${DOCKER_REGISTRY-}review
    build:
      context: .
      dockerfile: Services/Review/Dockerfile


  order:
    image: ${DOCKER_REGISTRY-}order
    build:
      context: .
      dockerfile: Services/Order/Dockerfile


  member:
    image: ${DOCKER_REGISTRY-}member
    build:
      context: .
      dockerfile: Services/Member/Dockerfile


  book:
    image: ${DOCKER_REGISTRY-}book
    build:
      context: .
      dockerfile: Services/Book/Dockerfile

